version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres 
    restart: unless-stopped
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: healthsoft_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports: 
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
      containter_name: prisma-postgres-api
      depends_on:
        - postgres
      ports:
        - "3000:3000"
      restart: always                  

volumes:
  postgres-data
  pgadmin-data
